### ISSUE TITLE
RPLSplit: Default should be to just produce RPLRaw objects for channels.

### ISSUE THREAD

**Issue by shihchengyen** [shihchengyen/PyHippocampus#15]

**Comment by anujsp2797** [comment]
Should there be LFP/HighPass/Sort flags for when the HPC is used? Or the HPC should call all three scripts?

**Comment by shihchengyen** [comment]
To have maximum flexibility, it might be good to have individual flags that you can select. Will the HPC flag be unnecessary since we can't not use HPC when we call RPLSplit call RPLLFP, RPLHighPass, Sort because of the recursive import problem, right?

**Comment by anujsp2797** [comment]
I've managed to get around the recursive import problem in the last commit -- therefore we can have RPLSplit call RPLLFP, RPLHighPass and sorting if required.

**Comment by shihchengyen** [comment]
Oh, okay. It will be good to have the option then.
