### ISSUE TITLE
RPLSplit: create function should check which directory it is in to figure out if is in a fixation session instead of requiring the SessionEye argument.

### ISSUE THREAD

**Issue by shihchengyen** [shihchengyen/PyHippocampus#16]
RPLSplit: create function should check which directory it is in to figure out if is in a fixation session instead of requiring the SessionEye argument.

This will allow us to just call DPT.objects.processDirs(None, pyh.RPLSplit, saveLevel=1) from the day directory for it to split the data for both the navigation and fixation sessions.

**Comment by anujsp2797** [comment]
I have removed the sessioneye argument and as of now, RPLSplit does the exact same process in both the navigation and eye sessions -- which is to create the rplraw file.
