### ISSUE TITLE
Unity: Trial Position Type should be included directly in Plot Option

### ISSUE THREAD

**Issue by shihchengyen** [shihchengyen/PyHippocampus#25]
X-Pos, Y-Pos, Orientation should be listed in Plot Option as X-T, Y-T, and Theta-T so we don't have to first select Trial Position in Plot Option, and then select another option in Trial Position Type.

**Comment by ChrischaoWang** [comment]
The Plot Option has been updated.

**Comment by shihchengyen** [comment]
Thanks! It works great!
